### ISSUE TITLE
Inclusion des liens website

### ISSUE THREAD

**Issue by Gagabouboule** [eldoniel/bpop-v1#4]
Si on peut faire des petites bulles twitter, Facebook, youtube, soundcloud (personnalisés avec le logo et la couleur de ces hébergeurs ce serait encore plus cool) et on y met nos pages

**Comment by eldoniel** [comment]
C'est déjà fait (mais sans les couleurs, le site n'étant (au moins pour l'instant) pas très coloré. On reparlera des couleurs plus tard, mais l'essentiel est fait, je ferme :)
