### ISSUE TITLE
Création de zones de lecture audio vidéo

### ISSUE THREAD

**Issue by Gagabouboule** [eldoniel/bpop-v1#5]
Si dans le site on fait des onglets vidéos et audios genre "Nos Vidéos" "Nous écouter" et dedans on y glisse l'URL directement des liens ou alors on peut directement télécharger nos vidéos et audios mp3

**Comment by eldoniel** [comment]
J'ai déjà un onglet "écoute" qui est fait, et qui s'embarrasse pas de liens puisqu'il embarque directement des lecteurs intégrés à la page. C'est encore en WIP notamment en termes d'organisation de la page, mais c'est facile à faire et en cours.
Pour les vidéos, je comptais mettre directement les vidéos Youtube lisibles depuis le site, et ce sera même probablement le premier truc que je ferai demain matin (vous devriez pouvoir regarder si vous êtes co).
Par contre, faudra réfléchir au nombre de vidéos dans une page, si on fait une page dédiée. Faut pas oublier que plusieurs vidéos dans une même page ça devient vite hyper chargé.
On rediscute tout ça quand vous aurez jeté un oeil au site en l'état actuel ;)

**Comment by eldoniel** [comment]
En fait, je réalise qu'on peut même pousser le cross-platform au maximum, parce que non seulement on peut inclure directement les vidéos youtube sur le site, mais on peut aussi inclure des chansons ou des playlists Soundcloud!

Pour cette dernière possibilité:
- Avantage: ça me fait du code foireux en moins, ça nous assure un peu plus qu'on viendra pas nous DL les chansons si on a pas envie (j'aurais ptet pu en code mais à voir). Et ça centralise les écoutes sur le Soundcloud et ça le fait tourner.
- Inconvénient: le jour où Soundcloud pète, on est niqués (mais je peux toujours garder un système de secours en backup au besoin).

**Comment by eldoniel** [comment]
Pour l'instant, géré par Soundcloud, on verra plus tard si on veut changer le système.
