### ISSUE TITLE
Likes

### ISSUE THREAD

**Issue by Gagabouboule** [eldoniel/bpop-v1#7]
C'est possible de faire relier le nombre de nos likes et abonnés Facebook au site ? et de l'afficher ? et en mode si quelqu'un tombe sur le site plutôt que le Facebook que lorsqu'il like ça affiche aussi sur Facebook et vice versa ?

**Comment by eldoniel** [comment]
Je sais que c'est possible, je l'ai déjà vu sur certains sites, faut que je trouve comment on fait.

**Comment by eldoniel** [comment]
Fait!
