### ISSUE TITLE
Suggestions d'interface du site web

### ISSUE THREAD

**Issue by Gagabouboule** [eldoniel/bpop-v1#8]
Check les sites web de metallica ou de sum 41, j'aime beaucoup. Tu n'as pas de page d'accueil avec "enter site", tu as tout, tout de suite : tu vois les onglets directement et les liens vers les autres sites, les news, une vidéos en gros de présentation et le petit plus du site des suis c'est que juste en-dessous du logo et je trouve que c'est judicieux tu as "enter your mail" en mode abonnement.
J'ai checks trivium, linkin park ou blink c'est moins lisible (linkin park c'est le pire), et je te parle même pas des couleurs fades du site de blink 182 !
L'idée : mettre en Gros le logo B!pop avec un "welcome", tout de suite en-dessous une barre pour s'abonnement en mode enter your mail, en dessous une vidéo de dingue, en dessous les news
Sur le côté on peut mettre la pochette de l'album avec les pistes avec lecture activables en même temps
et en-dessous ou au-dessus les onglets vers les autres sites hébergeurs et enfin au dessus les onglets merci, music, news, tour dates, repenses... blabla

**Comment by eldoniel** [comment]
Alors j'ai déjà fait un début d'interface un peu pas trop moche ;)
Metallica, j'aime pas ce genre de site, c'est trop le bordel.
Sum par contre, ouais ça le fait. Pour le coup, je me suis principalement inspiré du site de Rammstein, qui synthétise un peu tout de manière propre (un peu dans l'idée de Sum aussi), on a tout sous la main, mais de façon épurée.
Dans la semaine, je commencerai à vous mettre le site en test si vous voulez aller jeter un oeil!
